{
 "title": "Caretta Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "links_base",
    "label": "links base",
    "query": "(caretta_links_observed{client_namespace=~\"${namespace:regex}\", client_kind=~\"${kind:regex}\", client_name=~\"${workload:regex}\", server_port=~\"${port:regex}\"} or caretta_links_observed{server_namespace=~\"${namespace:regex}\", server_kind=~\"${kind:regex}\", server_name=~\"${workload:regex}\", server_port=~\"${port:regex}\"})"
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   {
    "name": "workload",
    "label": "workload",
    "query": {
     "query": "query_result(caretta_links_observed)"
    }
   },
   { "name": "port", "label": "server port", "query": { "query": "label_values(server_port)" } }
  ]
 },
 "panels": [
  {
   "title": "Service Map",
   "type": "nodeGraph",
   "gridPos": { "h": 24, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(\n  increase(\n    (\n      sum by (id, title, subTitle, detail__kind, arc__color) (\n        label_replace(\n          (\n            label_join(label_join(label_join(label_join(${links_base}, \"detail__kind\", \"\", \"server_kind\"), \"subTitle\", \"\", \"server_namespace\"), \"title\", \"\", \"server_name\"), \"id\", \"\", \"server_id\")\n            or\n            label_join(label_join(label_join(label_join(${links_base}, \"detail__kind\", \"\", \"client_kind\"), \"subTitle\", \"\", \"client_namespace\"), \"title\", \"\", \"client_name\"), \"id\", \"\", \"client_id\")\n          ),\n          \"arc__color\", \"1\", \"link_id\", \"(.*)\"\n        )\n      )\n    )[$__range:$__interval]\n  )\n) / 1048576 > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  rate(\n    (\n      (\n        sum by (id, source, target, detail__client_ip, detail__server_endpoint) (\n          label_join(label_join(label_join(label_join(label_join(${links_base}, \"source\", \"\", \"client_id\"), \"target\", \"\", \"server_id\"), \"id\", \"\", \"link_id\"), \"detail__client_ip\", \"\", \"client_ip\"), \"detail__server_endpoint\", \":\", \"server_ip\", \"server_port\")\n        )\n      )\n      and on(source)\n      sum by (source) (label_join(${links_base}, \"source\", \"\", \"client_id\"))\n      and on(target)\n      sum by (target) (label_join(${links_base}, \"target\", \"\", \"server_id\"))\n    )[$__range:$__interval]\n  ) / 1024\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Ports",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (server_port) (increase(${links_base}[$__range:$__interval]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \">\n<div style=\"text-align: center\">\n<p align=\"center\">\n  <img src=\"https://raw.githubusercontent.com/forza0310/caretta-rust/refs/heads/master/images/logo.png\" width=\"75%\" alt=\"caretta\" title=\"caretta\" />\n  <h4>by <a href=\"https://github.com/forza0310\">forza0310</h4>\n\n \n</div>\n</p>\n</div>\n</td>\n</table>\n"
   }
  },
  {
   "title": "Top Throughput Workloads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8, sum by (client_name) ((rate(caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\"}[$__range:$__interval]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Throughput Connections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7, sum by (client_name, server_name) ( rate( (caretta_links_observed{client_namespace=~\"$namespace\", client_kind=~\"$kind\", client_name=~\"$workload\", server_port=~\"$port\", client_kind!~\"(node|external)\",} or caretta_links_observed{server_namespace=~\"$namespace\", server_kind=~\"$kind\", server_name=~\"$workload\", server_port=~\"$port\", server_kind!~\"(node|external)\"})[$__range:$__interval]) ) )",
     "legendFormat": "{{client_name}} ⮂ {{server_name}}"
    }
   ]
  },
  {
   "title": "K8s Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "suffix:ops/min" } },
   "targets": [
    {
     "expr": "sum by (object_type) (rate(caretta_k8s_events_count{event_type=\"added\"}[$__rate_interval]) * 60)",
     "legendFormat": "added/{{object_type}}"
    },
    {
     "expr": "sum by (object_type) (rate(caretta_k8s_events_count{event_type=\"modified\"}[$__rate_interval]) * 60)",
     "legendFormat": "modified/{{object_type}}"
    },
    {
     "expr": "sum by (object_type) (rate(caretta_k8s_events_count{event_type=\"deleted\"}[$__rate_interval]) * 60)",
     "legendFormat": "deleted/{{object_type}}"
    }
   ]
  }
 ]
}